# Generated by Django 2.2.10 on 2020-02-23 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.TextField(max_length=14)),
                ('device_label', models.TextField(max_length=50)),
                ('pp_kg', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=16)),
                ('date_created', models.DateField(auto_now=True)),
                ('store_name', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='sales_track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.FloatField()),
                ('date_created', models.DateField(auto_now=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_sales_track.device_info')),
            ],
        ),
        migrations.AddField(
            model_name='device_info',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_sales_track.user_info'),
        ),
    ]
