# Generated by Django 2.2.10 on 2020-02-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_sales_track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_track',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
